### ISSUE TITLE
Errors in IOKitPlayground.playground

### ISSUE THREAD

**Issue by narner** [danielpi/SwiftSerialPortSample#1]
Hi Daniel! First off, this looks like a really useful project; I'm glad I came across it. 

Secondly, I wanted to let you know that when I opened up IOKitPlayground.playground, I got a few errors (screenshot below):

![screen shot 2015-06-27 at 12 48 09 pm](https://cloud.githubusercontent.com/assets/2131591/8393009/05c9180e-1ccb-11e5-8475-e6a8d5e762c8.png)

**Comment by danielpi** [comment]
HI Nick,

Thanks for having a look at my project. Hopefully it is useful for you. It looks like you are running an older version of the code though. The section you show above currently looks like this

![screen shot 2015-06-28 at 10 52 48 pm](https://cloud.githubusercontent.com/assets/483128/8396440/88512c1c-1de8-11e5-8bd4-a88179684aad.png)

If you grab the latest changes and give them a go you should be able to get ti running (with Xcode 7). Let me know if you have any issues.

**Comment by narner** [comment]
Hi Daniel, 

Thank you for your response! It looks as if I have pulled the latest changes, at least judging by SourceTree here:

![screen shot 2015-06-28 at 10 39 19 am](https://cloud.githubusercontent.com/assets/2131591/8396766/14ed1300-1d82-11e5-8bc2-ffe80bb88235.png)

It looks as if I still have that original code, though.

**Comment by danielpi** [comment]
That's a bit odd. The .takeUnretained() method calls were removed in the "Upgraded to XCode7":14a2f2a change back on the 16th. Could you try checking out another copy to a different folder to see if that fixes things?

**Comment by narner** [comment]
That is odd for sure! I just tried checking out a new copy in a different folder, as well as downloading a zip to my desktop; it the error still seems to be there in both places.

**Comment by danielpi** [comment]
I just downloaded a zip version and it had the right code which ran without errors.

I’ve attached a zip file with just the main swift file in it. Could you try sticking that into one of the projects and see if that has the right code in it.

**Comment by narner** [comment]
Ok, I will check that out! I can't seem to see the zip file though (my apologies!)

**Comment by danielpi** [comment]
Try downloading from this link https://www.dropbox.com/s/1v28zi7s94jk7n7/main.swift.zip?dl=0

Mustn't be able to send files through Github's email notifications system.

**Comment by narner** [comment]
Ah! Yes, not sure if I explained myself very well; that code all looks like it's up-to-date, as you said. It's just the error is in the Playground file.

**Comment by danielpi** [comment]
Ah ok, 

Yes the playground file isn’t in a good state. I love experimenting in Playground files so I’ve been keen to try and get some serial port code running in one (even though I’m not too sure what that would look like as the playground code gets re-executed multiple times which would be odd for serial comms). The current code in that file was for Xcode 6. I’ve tried to update it in my local repository but haven’t had much success and the file is basically blank at the moment. I plan on giving it another go at some point but can’t say when (or if It will be successful). 

If you want to experiment with it jump in and give it a go. The main.swift file has a lot of code that should work in a playground. Ultimately the whole project needs to be rearranged a bit though. You can’t access fcntl and ioctl directly from swift yet, so they have to go into an objective-c file and use a bridging header. This all then needs to go into a framework inside the project so that it can be imported into a playground. 

Just out of interest, what are you trying to do with a serial port? Not too many people out there using them these days.

Cheers
Daniel.

**Comment by narner** [comment]
Ah, I see; thanks for letting me know!

Basically, I'm trying to build an OS X project in Swift that will communicate with an Arduino over serial. I could probably just use a Bluetooth Shield (which is what I'm going to do for a future iOS project), but had wanted to use serial for the OS X one simply for learning it. 

I'll go ahead this issue now, but my email is nicholasarner (at) gmail (dot) com if you'd like to continue the conversation there. Thank you again, Daniel!
